### ISSUE TITLE
v0.8.5 or v0.8.4 or v0.8.3 or v0.8.1 or v0.8.0... not working?

### ISSUE THREAD

**Issue by itsazzad** [angular/batarang#248]
v0.8.5, v0.8.3, v0.8.1, v0.8.0: The AngularJS tab is showing empty.
v0.8.4: is saying, "The file or directory could not be found."
.
.
.
Google Chrome
Version 43.0.2357.134 (64-bit)
OS X Yosemite
10.10.3

**Comment by SomeKittens** [comment]
How are you testing this?  This issue was (hopefully) fixed in v0.8.5

**Comment by flight212121** [comment]
+1 here, same issue..

**Comment by itsazzad** [comment]
@SomeKittens Im following your instruction in the readme and installing in developer mode each version one after another after removing the previous versions.

**Comment by gary-b** [comment]
@flight212121 : I'm on Windows 8.1 with Chrome Version 44.0.2403.89 m and i'm not getting this issue with batarang 0.8.5.
 * What version of batarang are you on? 
 * Are you getting a white page or the file not found error message? 
 * Assuming you are not on 0.8.4, can you try refreshing the web page after the batarang tab in dev tools has been opened?
 * Does the tab still have the issue when debugging this app: http://gary-b.github.io/WF4JSDesigner/

**Comment by gary-b** [comment]
@itsazzad It would be interesting to see if 0.8.5 from the web store is working for you https://chrome.google.com/webstore/detail/angularjs-batarang/ighdmehidhipcmcojjgiloacoafjmpfk?hl=en

Note, if its blank when you first open the batarang tab just refresh the page.

**Comment by itsazzad** [comment]
![screen shot 2015-07-23 at 10 07 51 am](https://cloud.githubusercontent.com/assets/54909/8842970/14c87fae-3123-11e5-813d-35627d9790fd.png)
![screen shot 2015-07-23 at 10 08 20 am](https://cloud.githubusercontent.com/assets/54909/8842972/1a8f5fc0-3123-11e5-9f58-a6e9e0e73c57.png)

Now it certainly does not look like the extension video ( https://www.youtube.com/watch?v=q-7mhcHXSfM ). Am i missing something?

Im using https://chrome.google.com/webstore/detail/angularjs-batarang-stable/niopocochgahfkiccpjmmpchncjoapek 0.4.3 and its working

**Comment by flight212121** [comment]
@gary-b thanks for your reply

> * What version of batarang are you on?

I was getting a blank page before but I tried 0.8.5 again this morning, it worked, got the same screen as @itsazzad here:

![](https://cloud.githubusercontent.com/assets/54909/8842972/1a8f5fc0-3123-11e5-9f58-a6e9e0e73c57.png)

 > * Does the tab still have the issue when debugging this app: http://gary-b.github.io/WF4JSDesigner/

![image](https://cloud.githubusercontent.com/assets/9644867/8854038/d2a52196-312b-11e5-9a68-fdf80f8e1fed.png)

This one works as well for me:
https://chrome.google.com/webstore/detail/angularjs-batarang-stable/niopocochgahfkiccpjmmpchncjoapek

**Comment by gary-b** [comment]
Yeah batarang went though a some changes after 0.4.3 and the UI looks quite different now. The video on the web store hasn't been updated to reflect this. I guess the focus of limited resources has been elsewhere.

**Comment by SomeKittens** [comment]
Ah, this is the dev version?  Things get ... complicated there.  Closing this issue if the store version works, as setting up the dev version isn't supported right now - though I've opened #251 to track that.

Thanks!
